source 'https://rubygems.org'

ruby '2.2.1'

gem 'rails',                              '4.2.1'
gem 'sqlite3',                            '1.3.10'
gem 'sass-rails',                         '5.0.3'
gem 'uglifier',                           '2.7.1'
gem 'coffee-rails',                       '4.1.0'
gem 'jquery-rails',                       '4.0.3'
gem 'turbolinks',                         '2.5.3'
gem 'jbuilder',                           '2.2.12'
gem 'binding_of_caller',                  '0.7.3.pre1'
gem 'globalize',                          '5.0.1'

group :development, :test do
  gem 'byebug',                           '4.0.4'
  gem 'web-console',                      '2.1.2'
  gem 'spring',                           '1.3.3'
end

gem 'spree'
gem 'spree_gateway',                      github: 'spree/spree_gateway',                branch: '3-0-stable'
gem 'spree_auth_devise',                  github: 'spree/spree_auth_devise',            branch: '3-0-stable'
gem 'spree_i18n',                         github: 'spree-contrib/spree_i18n',           branch: '3-0-stable'
gem 'deface'
# fixed it spree-static-content
# https://github.com/pero-ict-solutions/spree-static-content.git
gem 'spree_static_content',               '3.0.0'
# gem 'spree_multilingual_static_content',  '3.0.0'

# gem "spree_product_zoom",                 '3.0.0'
# gem "spree_env_ribbon",                   '3.0.0'
# NONE gem 'spree_fancy',                        github: 'spree/spree_fancy',                  branch: '3-0-stable'
# NONE gem 'spree_product_zoom',                 github: 'spree/spree_product_zoom',           branch: '3-0-stable'

