source 'https://rubygems.org'

ruby '2.1.3'

gem 'rails',                  '4.2.0'
gem 'sqlite3'
gem 'ransack',                '~> 1.4.1'
gem 'tilt',                   '~> 1.4.1'
gem 'rabl',                   '~> 0.9.4.pre1'
gem 'sass-rails',             '~> 5.0'
gem 'uglifier',               '~> 2.7.0'
gem 'coffee-rails',           '~> 4.1.0'
gem 'jquery-rails',           '~> 4.0'
gem 'turbolinks',             '~> 2.5.3'
gem 'jbuilder',               '~> 2.0'
gem 'select2-rails',          '~> 3.5.9.1'

# install spree
gem 'spree', github: 'spree/spree', branch: '3-0-stable'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '3-0-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '3-0-stable'
gem 'spree_i18n', github: 'spree-contrib/spree_i18n', branch: '3-0-stable'
# gem 'spree_fancy', github: 'spree/spree_fancy', branch: 'master'
# gem 'spree_product_zoom', github: 'spree/spree_product_zoom'

group :development, :test do
  gem 'byebug'
  gem 'web-console',          '~> 2.1.1'
  gem 'spring'
end
